name: my_first_github_action

on:
  # push:
    # branches:
       # - master
  workflow_dispatch:
    inputs:
      parameter:
        description: My Parameter

jobs:
   hello:
      runs-on: ubuntu-latest
      steps:
         - name: hello world
           run: echo "${{ inputs.parameter }}"
