name: my_first_github_action

on:
  workflow_dispatch:
    inputs:
      helm_chart:
        description: helm_chart
      version:
         description: my_version
      chart_name:
         description: chart_name
jobs:
   hello:
      runs-on: ubuntu-latest
      steps:
         - name: hello world
           run: echo "${{ GITHUB_ACTIONS }}"
         - name: install plugin
           uses: WyriHaximus/github-action-helm3@v3
           with:
             exec: helm plugin install https://github.com/nikhilsbhat/helm-images
         - name: add repo
           uses: WyriHaximus/github-action-helm3@v3
           with:
             exec: helm repo add my-repo "${{ inputs.helm_chart }}"
         - name: pull repo
           uses: WyriHaximus/github-action-helm3@v3
           with:
             exec: helm pull my-repo/"${{ inputs.chart_name }}" --version "${{ inputs.version }}"
         - name: List Images
           uses: WyriHaximus/github-action-helm3@v3
           with:
             exec: helm images get "reloader-${{ inputs.version }}.tgz"
             
