name: my_first_github_action

on:
  workflow_dispatch:
    inputs:
      parameter:
        description: helm_chart

jobs:
   hello:
      runs-on: ubuntu-latest
      steps:
         - name: hello world
           run: chmod 400 ~/.kube/config
         - name: install plugin
           uses: WyriHaximus/github-action-helm3@v3
           with:
             exec: helm plugin install https://github.com/nikhilsbhat/helm-images
         - name: add repo
           uses: WyriHaximus/github-action-helm3@v3
           with:
             exec: helm repo add my-repo "${{ inputs.parameter }}"
         - name: pull repo
           uses: WyriHaximus/github-action-helm3@v3
           with:
             exec: helm pull my-repo/reloader
         - name: List Images
           uses: WyriHaximus/github-action-helm3@v3
           with:
             exec: helm images get reloader-1.0.116.tgz
             
