name: my_first_github_action

on:
  workflow_dispatch:
    inputs:
      parameter:
        description: helm_chart

jobs:
   hello:
      runs-on: ubuntu-latest
      steps:
         - name: hello world
           run: echo "${{ inputs.helm_chart }}"
         - name: install plugin
           uses: WyriHaximus/github-action-helm3@v3
           with:
             exec: helm plugin install https://github.com/nikhilsbhat/helm-images
         - name: install plugin
           uses: WyriHaximus/github-action-helm3@v3
           with:
             exec: helm repo add my-repo "${{ inputs.helm_chart }}"
             
